"""Preview quality tests — layout-agnostic.

Validates that the HTML previews generated by orren_engine.preview are:
  - Syntactically valid HTML (parseable by html.parser)
  - Self-contained (inline CSS + JS, no external dependencies)
  - Structurally complete (header, content, footer)
  - Visually meaningful (entities rendered, vibes applied, scores shown)
  - Displayable in any modern browser

These tests are LAYOUT-AGNOSTIC: they check that the *content* is present
(preservation scores, equilibrium rules, entity names) without asserting
specific CSS class names, because different layout strategies (document,
dashboard, app, atmospheric, schematic) use different markup.

Run: pytest tests/test_12_preview_quality.py -v
"""
import html.parser
import os
import sys

sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))

import pytest

from orren_engine import Engine, generate_preview, write_preview, extract_design_tokens

PREVIEWS_DIR = os.path.abspath(
    os.path.join(os.path.dirname(__file__), "..", "download", "previews")
)

ALL_EXAMPLES = [
    ("examples/01_irrigation.orn",            "01_irrigation"),
    ("examples/02_news_researcher.orn",       "02_news_researcher"),
    ("examples/03_farmer_dashboard.orn",      "03_farmer_dashboard"),
    ("examples/04_farm_management.orn",       "04_farm_management"),
    ("examples/05_greenhouse_controller.orn", "05_greenhouse_controller"),
    ("examples/06_tell_your_story.orn",       "06_tell_your_story"),
    ("examples/07_master_builder_book.orn",   "07_master_builder_book"),
    ("examples/adversarial/01_rain_composition.orn",  "adv_01_rain_composition"),
    ("examples/adversarial/02_assistive_arm.orn",     "adv_02_assistive_arm"),
    ("examples/adversarial/03_revenue_contract.orn",  "adv_03_revenue_contract"),
    ("examples/adversarial/04_lighthouse.orn",        "adv_04_lighthouse"),
    ("examples/adversarial/05_sign_bridge.orn",       "adv_05_sign_bridge"),
    ("examples/adversarial/06_still_water.orn",       "adv_06_still_water"),
]


def _load_and_run(src_path):
    full_path = os.path.join(os.path.dirname(__file__), "..", src_path)
    with open(full_path) as f:
        src = f.read()
    engine = Engine()
    result = engine.run(src)
    return result


# ---------------------------------------------------------------------------
# HTML validity
# ---------------------------------------------------------------------------


class _HTMLValidator(html.parser.HTMLParser):
    def __init__(self):
        super().__init__()
        self.tag_stack = []
        self.errors = []

    def handle_starttag(self, tag, attrs):
        if tag not in ("meta", "link", "br", "hr", "img", "input"):
            self.tag_stack.append(tag)

    def handle_endtag(self, tag):
        if not self.tag_stack:
            self.errors.append(f"unexpected </{tag}>")
            return
        if self.tag_stack[-1] != tag:
            self.errors.append(f"mismatched: expected </{self.tag_stack[-1]}> got </{tag}>")
        else:
            self.tag_stack.pop()


def _validate_html(html_str):
    v = _HTMLValidator()
    v.feed(html_str)
    return v.errors


class TestHTMLValidity:
    @pytest.mark.parametrize("src_path,label", ALL_EXAMPLES)
    def test_preview_is_valid_html(self, src_path, label):
        result = _load_and_run(src_path)
        html_str = generate_preview(result.graph, artifacts=result.artifacts)
        errors = _validate_html(html_str)
        assert not errors, f"{label}: HTML errors: {errors[:3]}"

    @pytest.mark.parametrize("src_path,label", ALL_EXAMPLES)
    def test_preview_starts_with_doctype(self, src_path, label):
        result = _load_and_run(src_path)
        html_str = generate_preview(result.graph, artifacts=result.artifacts)
        assert html_str.startswith("<!DOCTYPE html>")

    @pytest.mark.parametrize("src_path,label", ALL_EXAMPLES)
    def test_preview_has_html_root(self, src_path, label):
        result = _load_and_run(src_path)
        html_str = generate_preview(result.graph, artifacts=result.artifacts)
        assert "<html" in html_str
        assert "</html>" in html_str


# ---------------------------------------------------------------------------
# Self-containment
# ---------------------------------------------------------------------------


class TestSelfContained:
    @pytest.mark.parametrize("src_path,label", ALL_EXAMPLES)
    def test_no_external_dependencies(self, src_path, label):
        result = _load_and_run(src_path)
        html_str = generate_preview(result.graph, artifacts=result.artifacts)
        # No external stylesheet links (other than the inline <style> block).
        assert 'href="styles.css"' not in html_str
        # No external script src.
        assert '<script src=' not in html_str
        # No external font links.
        assert "fonts.googleapis.com" not in html_str
        assert "cdn.jsdelivr" not in html_str

    @pytest.mark.parametrize("src_path,label", ALL_EXAMPLES)
    def test_has_inline_css(self, src_path, label):
        result = _load_and_run(src_path)
        html_str = generate_preview(result.graph, artifacts=result.artifacts)
        assert "<style>" in html_str
        assert "</style>" in html_str

    @pytest.mark.parametrize("src_path,label", ALL_EXAMPLES)
    def test_has_inline_js(self, src_path, label):
        result = _load_and_run(src_path)
        html_str = generate_preview(result.graph, artifacts=result.artifacts)
        assert "<script>" in html_str
        assert "</script>" in html_str


# ---------------------------------------------------------------------------
# Structural completeness (layout-agnostic — tests for content, not class names)
# ---------------------------------------------------------------------------


class TestStructuralCompleteness:
    @pytest.mark.parametrize("src_path,label", ALL_EXAMPLES)
    def test_contains_app_name(self, src_path, label):
        result = _load_and_run(src_path)
        html_str = generate_preview(result.graph, artifacts=result.artifacts)
        assert result.graph.root.name in html_str

    @pytest.mark.parametrize("src_path,label", ALL_EXAMPLES)
    def test_contains_purpose_text(self, src_path, label):
        result = _load_and_run(src_path)
        html_str = generate_preview(result.graph, artifacts=result.artifacts)
        # Find the purpose from the root expression dimension.
        purpose = ""
        for entry in result.graph.root.get_dimension(__import__("orren_engine").Dimension.EXPRESSION):
            if isinstance(entry, dict) and entry.get("key") == "purpose":
                purpose = str(entry.get("value", ""))
                break
        if purpose:
            # At least the first few words of the purpose should appear.
            first_words = purpose[:30]
            assert first_words in html_str, f"{label}: purpose text not in preview"

    @pytest.mark.parametrize("src_path,label", ALL_EXAMPLES)
    def test_contains_entity_names(self, src_path, label):
        result = _load_and_run(src_path)
        html_str = generate_preview(result.graph, artifacts=result.artifacts)
        # At least 3 entity names should appear in the preview.
        found = 0
        for node in result.graph.nodes[:10]:
            if node.name in html_str:
                found += 1
        assert found >= 3, f"{label}: only {found} entity names found in preview"

    @pytest.mark.parametrize("src_path,label", ALL_EXAMPLES)
    def test_contains_orren_version(self, src_path, label):
        result = _load_and_run(src_path)
        html_str = generate_preview(result.graph, artifacts=result.artifacts)
        from orren_engine import __version__
        assert __version__ in html_str


# ---------------------------------------------------------------------------
# Visual meaningfulness (content checks, not class checks)
# ---------------------------------------------------------------------------


class TestVisualMeaningfulness:
    @pytest.mark.parametrize("src_path,label", ALL_EXAMPLES)
    def test_preservation_scores_present(self, src_path, label):
        """Each realization target's preservation score should appear
        somewhere in the preview."""
        result = _load_and_run(src_path)
        html_str = generate_preview(result.graph, artifacts=result.artifacts)
        for art in result.artifacts:
            score_str = f"{art.preservation_score:.2f}"
            assert score_str in html_str, (
                f"{label}: preservation score {score_str} for {art.target_name} not in preview"
            )

    @pytest.mark.parametrize("src_path,label", ALL_EXAMPLES)
    def test_target_names_present(self, src_path, label):
        result = _load_and_run(src_path)
        html_str = generate_preview(result.graph, artifacts=result.artifacts)
        for art in result.artifacts:
            assert art.target_name in html_str, (
                f"{label}: target name {art.target_name} not in preview"
            )

    @pytest.mark.parametrize("src_path,label", ALL_EXAMPLES)
    def test_node_count_present(self, src_path, label):
        result = _load_and_run(src_path)
        html_str = generate_preview(result.graph, artifacts=result.artifacts)
        # The node count should appear as a stat somewhere.
        assert str(result.sir_node_count) in html_str or str(len(result.graph.nodes)) in html_str

    @pytest.mark.parametrize("src_path,label", ALL_EXAMPLES)
    def test_css_uses_design_tokens(self, src_path, label):
        """The CSS should reference design token CSS variables."""
        result = _load_and_run(src_path)
        html_str = generate_preview(result.graph, artifacts=result.artifacts)
        assert "var(--" in html_str, f"{label}: CSS doesn't use design tokens"
        assert "var(--bg)" in html_str or "var(--accent)" in html_str

    @pytest.mark.parametrize("src_path,label", ALL_EXAMPLES)
    def test_layout_strategy_applied(self, src_path, label):
        """The design tokens' layout_strategy should be reflected in the HTML."""
        result = _load_and_run(src_path)
        tokens = extract_design_tokens(result.graph)
        html_str = generate_preview(result.graph, artifacts=result.artifacts)
        # Each layout strategy produces distinct CSS class patterns.
        strategy_markers = {
            "document": ["document-page", "doc-header", "doc-body"],
            "dashboard": ["layout-dashboard", "app-header", "canvas-panel"],
            "app": ["layout-app", "app-canvas", "app-panels"],
            "atmospheric": ["atmospheric-scene", "atmospheric-header", "atmosphere-grid"],
            "schematic": ["layout-schematic", "schematic-canvas", "sch-component"],
        }
        markers = strategy_markers.get(tokens.layout_strategy, [])
        if markers:
            found_any = any(m in html_str for m in markers)
            assert found_any, (
                f"{label}: layout strategy {tokens.layout_strategy} markers not found"
            )


# ---------------------------------------------------------------------------
# File output
# ---------------------------------------------------------------------------


class TestFileOutput:
    @pytest.mark.parametrize("label", [lbl for _, lbl in ALL_EXAMPLES])
    def test_preview_file_exists(self, label):
        path = os.path.join(PREVIEWS_DIR, f"{label}.html")
        assert os.path.isfile(path), f"missing preview: {path}"

    @pytest.mark.parametrize("label", [lbl for _, lbl in ALL_EXAMPLES])
    def test_preview_file_nonempty(self, label):
        path = os.path.join(PREVIEWS_DIR, f"{label}.html")
        size = os.path.getsize(path)
        assert size > 5000, f"{label}: only {size} bytes (too small)"

    def test_write_preview_to_temp_file(self, tmp_path):
        full_path = os.path.join(
            os.path.dirname(__file__), "..",
            "examples/06_tell_your_story.orn"
        )
        with open(full_path) as f:
            src = f.read()
        engine = Engine()
        result = engine.run(src)
        out = tmp_path / "test.html"
        write_preview(result.graph, str(out), artifacts=result.artifacts)
        assert out.exists()
        content = out.read_text()
        assert "<!DOCTYPE html>" in content


# ---------------------------------------------------------------------------
# Stability
# ---------------------------------------------------------------------------


class TestPreviewStability:
    def test_same_input_same_output(self):
        full_path = os.path.join(
            os.path.dirname(__file__), "..",
            "examples/06_tell_your_story.orn"
        )
        with open(full_path) as f:
            src = f.read()
        engine = Engine()
        result = engine.run(src)
        html1 = generate_preview(result.graph, artifacts=result.artifacts)
        engine2 = Engine()
        result2 = engine2.run(src)
        html2 = generate_preview(result2.graph, artifacts=result2.artifacts)
        assert html1 == html2


# ---------------------------------------------------------------------------
# Equilibrium content (when present)
# ---------------------------------------------------------------------------


class TestEquilibriumContent:
    @pytest.mark.parametrize("src_path,label", ALL_EXAMPLES)
    def test_equilibrium_rules_mentioned(self, src_path, label):
        """If the graph has equilibrium rules, their names should appear
        somewhere in the preview (in the equilibrium panel or as
        badges on entity cards)."""
        result = _load_and_run(src_path)
        if not result.graph.equilibrium_rules:
            return
        html_str = generate_preview(result.graph, artifacts=result.artifacts)
        # At least half of the rule names should be in the preview.
        found = sum(1 for r in result.graph.equilibrium_rules if r.name in html_str)
        total = len(result.graph.equilibrium_rules)
        assert found >= total * 0.5, (
            f"{label}: only {found}/{total} equilibrium rule names in preview"
        )
