"""Preview quality tests.

Validates that the HTML previews generated by orren_engine.preview are:
  - Syntactically valid HTML (parseable by html.parser)
  - Self-contained (inline CSS + JS, no external dependencies)
  - Structurally complete (header, structure tree, canvas, info panels)
  - Visually meaningful (entity cards with applied vibes, badges, panels)
  - Displayable in any modern browser

Run: pytest tests/test_12_preview_quality.py -v
"""
import html.parser
import os
import sys

sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))

import pytest

from orren_engine import Engine, generate_preview, write_preview

PREVIEWS_DIR = os.path.abspath(
    os.path.join(os.path.dirname(__file__), "..", "download", "previews")
)

ALL_EXAMPLES = [
    ("examples/01_irrigation.orn",            "01_irrigation"),
    ("examples/02_news_researcher.orn",       "02_news_researcher"),
    ("examples/03_farmer_dashboard.orn",      "03_farmer_dashboard"),
    ("examples/04_farm_management.orn",       "04_farm_management"),
    ("examples/05_greenhouse_controller.orn", "05_greenhouse_controller"),
    ("examples/06_tell_your_story.orn",       "06_tell_your_story"),
    ("examples/07_master_builder_book.orn",   "07_master_builder_book"),
    ("examples/adversarial/01_rain_composition.orn",  "adv_01_rain_composition"),
    ("examples/adversarial/02_assistive_arm.orn",     "adv_02_assistive_arm"),
    ("examples/adversarial/03_revenue_contract.orn",  "adv_03_revenue_contract"),
    ("examples/adversarial/04_lighthouse.orn",        "adv_04_lighthouse"),
    ("examples/adversarial/05_sign_bridge.orn",       "adv_05_sign_bridge"),
    ("examples/adversarial/06_still_water.orn",       "adv_06_still_water"),
]


# ---------------------------------------------------------------------------
# HTML validity
# ---------------------------------------------------------------------------


class _HTMLValidator(html.parser.HTMLParser):
    def __init__(self):
        super().__init__()
        self.tag_stack = []
        self.errors = []

    def handle_starttag(self, tag, attrs):
        # Void elements don't need closing
        if tag not in ("meta", "link", "br", "hr", "img", "input"):
            self.tag_stack.append(tag)

    def handle_endtag(self, tag):
        if not self.tag_stack:
            self.errors.append(f"unexpected </{tag}>")
            return
        if self.tag_stack[-1] != tag:
            self.errors.append(f"mismatched: expected </{self.tag_stack[-1]}> got </{tag}>")
        else:
            self.tag_stack.pop()


def _validate_html(html_str):
    v = _HTMLValidator()
    v.feed(html_str)
    return v.errors


class TestHTMLValidity:
    @pytest.mark.parametrize("src_path,label", ALL_EXAMPLES)
    def test_preview_is_valid_html(self, src_path, label):
        full_path = os.path.join(os.path.dirname(__file__), "..", src_path)
        with open(full_path) as f:
            src = f.read()
        engine = Engine()
        result = engine.run(src)
        html_str = generate_preview(result.graph, artifacts=result.artifacts)
        errors = _validate_html(html_str)
        assert not errors, f"{label}: HTML errors: {errors[:3]}"

    @pytest.mark.parametrize("src_path,label", ALL_EXAMPLES)
    def test_preview_starts_with_doctype(self, src_path, label):
        full_path = os.path.join(os.path.dirname(__file__), "..", src_path)
        with open(full_path) as f:
            src = f.read()
        engine = Engine()
        result = engine.run(src)
        html_str = generate_preview(result.graph, artifacts=result.artifacts)
        assert html_str.startswith("<!DOCTYPE html>")

    @pytest.mark.parametrize("src_path,label", ALL_EXAMPLES)
    def test_preview_has_html_root(self, src_path, label):
        full_path = os.path.join(os.path.dirname(__file__), "..", src_path)
        with open(full_path) as f:
            src = f.read()
        engine = Engine()
        result = engine.run(src)
        html_str = generate_preview(result.graph, artifacts=result.artifacts)
        assert "<html" in html_str
        assert "</html>" in html_str


# ---------------------------------------------------------------------------
# Self-containment
# ---------------------------------------------------------------------------


class TestSelfContained:
    @pytest.mark.parametrize("src_path,label", ALL_EXAMPLES)
    def test_no_external_dependencies(self, src_path, label):
        """The preview must not reference any external CSS, JS, or fonts."""
        full_path = os.path.join(os.path.dirname(__file__), "..", src_path)
        with open(full_path) as f:
            src = f.read()
        engine = Engine()
        result = engine.run(src)
        html_str = generate_preview(result.graph, artifacts=result.artifacts)
        # No external stylesheet links.
        assert 'rel="stylesheet"' not in html_str or 'href="styles.css"' not in html_str
        # No external script src.
        assert '<script src=' not in html_str
        # No external font links.
        assert "fonts.googleapis.com" not in html_str
        assert "cdn.jsdelivr" not in html_str

    @pytest.mark.parametrize("src_path,label", ALL_EXAMPLES)
    def test_has_inline_css(self, src_path, label):
        full_path = os.path.join(os.path.dirname(__file__), "..", src_path)
        with open(full_path) as f:
            src = f.read()
        engine = Engine()
        result = engine.run(src)
        html_str = generate_preview(result.graph, artifacts=result.artifacts)
        assert "<style>" in html_str
        assert "</style>" in html_str

    @pytest.mark.parametrize("src_path,label", ALL_EXAMPLES)
    def test_has_inline_js(self, src_path, label):
        full_path = os.path.join(os.path.dirname(__file__), "..", src_path)
        with open(full_path) as f:
            src = f.read()
        engine = Engine()
        result = engine.run(src)
        html_str = generate_preview(result.graph, artifacts=result.artifacts)
        assert "<script>" in html_str
        assert "</script>" in html_str


# ---------------------------------------------------------------------------
# Structural completeness
# ---------------------------------------------------------------------------


class TestStructuralCompleteness:
    @pytest.mark.parametrize("src_path,label", ALL_EXAMPLES)
    def test_has_header_with_app_name(self, src_path, label):
        full_path = os.path.join(os.path.dirname(__file__), "..", src_path)
        with open(full_path) as f:
            src = f.read()
        engine = Engine()
        result = engine.run(src)
        html_str = generate_preview(result.graph, artifacts=result.artifacts)
        assert "app-header" in html_str
        assert result.graph.root.name in html_str

    @pytest.mark.parametrize("src_path,label", ALL_EXAMPLES)
    def test_has_structure_panel(self, src_path, label):
        full_path = os.path.join(os.path.dirname(__file__), "..", src_path)
        with open(full_path) as f:
            src = f.read()
        engine = Engine()
        result = engine.run(src)
        html_str = generate_preview(result.graph, artifacts=result.artifacts)
        assert "structure-panel" in html_str
        assert "tree" in html_str

    @pytest.mark.parametrize("src_path,label", ALL_EXAMPLES)
    def test_has_canvas_panel(self, src_path, label):
        full_path = os.path.join(os.path.dirname(__file__), "..", src_path)
        with open(full_path) as f:
            src = f.read()
        engine = Engine()
        result = engine.run(src)
        html_str = generate_preview(result.graph, artifacts=result.artifacts)
        assert "canvas-panel" in html_str

    @pytest.mark.parametrize("src_path,label", ALL_EXAMPLES)
    def test_has_info_panel(self, src_path, label):
        full_path = os.path.join(os.path.dirname(__file__), "..", src_path)
        with open(full_path) as f:
            src = f.read()
        engine = Engine()
        result = engine.run(src)
        html_str = generate_preview(result.graph, artifacts=result.artifacts)
        assert "info-panel" in html_str


# ---------------------------------------------------------------------------
# Visual meaningfulness
# ---------------------------------------------------------------------------


class TestVisualMeaningfulness:
    @pytest.mark.parametrize("src_path,label", ALL_EXAMPLES)
    def test_entity_cards_present(self, src_path, label):
        full_path = os.path.join(os.path.dirname(__file__), "..", src_path)
        with open(full_path) as f:
            src = f.read()
        engine = Engine()
        result = engine.run(src)
        html_str = generate_preview(result.graph, artifacts=result.artifacts)
        # At least one entity card should be present.
        assert html_str.count("entity-card") >= 1

    @pytest.mark.parametrize("src_path,label", ALL_EXAMPLES)
    def test_dimension_badges_present(self, src_path, label):
        full_path = os.path.join(os.path.dirname(__file__), "..", src_path)
        with open(full_path) as f:
            src = f.read()
        engine = Engine()
        result = engine.run(src)
        html_str = generate_preview(result.graph, artifacts=result.artifacts)
        assert "dim-badge" in html_str

    @pytest.mark.parametrize("src_path,label", ALL_EXAMPLES)
    def test_preservation_scores_displayed(self, src_path, label):
        full_path = os.path.join(os.path.dirname(__file__), "..", src_path)
        with open(full_path) as f:
            src = f.read()
        engine = Engine()
        result = engine.run(src)
        html_str = generate_preview(result.graph, artifacts=result.artifacts)
        assert "preservation" in html_str.lower()

    def test_equilibrium_panel_shows_rules(self):
        # Use the rain composition which has 6+ rules.
        full_path = os.path.join(
            os.path.dirname(__file__), "..",
            "examples/adversarial/01_rain_composition.orn"
        )
        with open(full_path) as f:
            src = f.read()
        engine = Engine()
        result = engine.run(src)
        html_str = generate_preview(result.graph, artifacts=result.artifacts)
        # Each rule should appear.
        for rule in result.graph.equilibrium_rules:
            assert rule.name in html_str


# ---------------------------------------------------------------------------
# File output
# ---------------------------------------------------------------------------


class TestFileOutput:
    @pytest.mark.parametrize("label", [lbl for _, lbl in ALL_EXAMPLES])
    def test_preview_file_exists(self, label):
        """All 13 preview files should have been generated."""
        path = os.path.join(PREVIEWS_DIR, f"{label}.html")
        assert os.path.isfile(path), f"missing preview: {path}"

    @pytest.mark.parametrize("label", [lbl for _, lbl in ALL_EXAMPLES])
    def test_preview_file_nonempty(self, label):
        path = os.path.join(PREVIEWS_DIR, f"{label}.html")
        size = os.path.getsize(path)
        assert size > 5000, f"{label}: only {size} bytes (too small)"

    def test_write_preview_to_temp_file(self, tmp_path):
        # Test the write_preview function.
        full_path = os.path.join(
            os.path.dirname(__file__), "..",
            "examples/06_tell_your_story.orn"
        )
        with open(full_path) as f:
            src = f.read()
        engine = Engine()
        result = engine.run(src)
        out = tmp_path / "test.html"
        write_preview(result.graph, str(out), artifacts=result.artifacts)
        assert out.exists()
        content = out.read_text()
        assert "<!DOCTYPE html>" in content


# ---------------------------------------------------------------------------
# Stability
# ---------------------------------------------------------------------------


class TestPreviewStability:
    def test_same_input_same_output(self):
        full_path = os.path.join(
            os.path.dirname(__file__), "..",
            "examples/06_tell_your_story.orn"
        )
        with open(full_path) as f:
            src = f.read()
        engine = Engine()
        result = engine.run(src)
        html1 = generate_preview(result.graph, artifacts=result.artifacts)
        # Re-run from scratch.
        engine2 = Engine()
        result2 = engine2.run(src)
        html2 = generate_preview(result2.graph, artifacts=result2.artifacts)
        assert html1 == html2
