"""Optional bundler scaffolding for premium web targets.

Emitted ONLY when a web target explicitly declares the ``bundler``
capability.  Orren's default promise is "no build step"; the bundler layer is
an additive convenience for teams that want Vite tooling around the generated
three-file bundle — never a requirement.

Generated files (under the target directory):
    - ``package.json``     scripts: dev / build / preview / test
    - ``vite.config.js``   serves and builds from the target directory
    - ``tests/smoke.spec.js``  Playwright smoke test of the running bundle

The generator itself has zero dependencies; it only writes text files.
"""

from typing import Dict

from ..data_model import RealizationTarget, SIRGraph

_VITE_CONFIG = """// Generated by Orren — Vite config for the bundled workflow.
// The plain three-file build works without any of this; see index.html.
import { defineConfig } from 'vite';

export default defineConfig({
  root: '.',
  base: './',
  build: {
    outDir: 'dist',
    rollupOptions: {
      input: {
        main: 'index.html',
      },
    },
  },
  server: { open: true },
});
"""

_PACKAGE_JSON = """{
  "name": "@orren/generated-app",
  "private": true,
  "version": "0.0.0",
  "type": "module",
  "description": "Orren-generated web application (bundler workflow)",
  "scripts": {
    "dev": "vite",
    "build": "vite build",
    "preview": "vite preview",
    "test": "playwright test"
  },
  "devDependencies": {
    "vite": "^5.0.0",
    "@playwright/test": "^1.40.0"
  }
}
"""

_SMOKE_SPEC = """// Generated by Orren — Playwright smoke test for the bundled app.
import { test, expect } from '@playwright/test';

test('application boots without unhandled errors', async ({ page }) => {
  const errors = [];
  page.on('pageerror', (err) => errors.push(String(err)));
  await page.goto('/');
  await expect(page.locator('#orren-root')).toBeVisible();
  await expect(page.locator('#orren-error-boundary')).toBeHidden();
  expect(errors).toEqual([]);
});

test('theme toggle flips aria-pressed', async ({ page }) => {
  await page.goto('/');
  const toggle = page.locator('#orren-theme-toggle');
  if (await toggle.count()) {
    await toggle.click();
    await expect(toggle).toHaveAttribute('aria-pressed', 'true');
  }
});
"""


def bundler_requested(target: RealizationTarget) -> bool:
    """True when the target explicitly opts in to the bundler workflow."""
    return "bundler" in [c.lower() for c in target.capabilities]


def generate_bundler_files(graph: SIRGraph, target: RealizationTarget) -> Dict[str, str]:
    """Return bundler scaffolding keyed by artifact path.

    Returns an empty dict unless the target declares the ``bundler``
    capability — the no-build-step promise stays the default.
    """
    if not bundler_requested(target):
        return {}
    return {
        f"{target.name}/package.json": _PACKAGE_JSON,
        f"{target.name}/vite.config.js": _VITE_CONFIG,
        f"{target.name}/tests/smoke.spec.js": _SMOKE_SPEC,
    }


__all__ = ["generate_bundler_files", "bundler_requested"]
