from __future__ import annotations
import hashlib, re, shlex
from .field import DIMENSIONS, SIRField, SIRNode, ResolutionNode, Provenance, uid, now

class Agent:
    name = "agent"
    def __init__(self, field): self.field = field
    async def on_event(self, event): raise NotImplementedError

class TextProducer(Agent):
    name = "text_producer"
    async def inject(self, source):
        tokens = [m.group(0) for m in re.finditer(r"([A-Za-z_][\w-]*)|[{}]", source.strip())]
        stack, created, i = [], [], 0
        source_hash = hashlib.sha256(source.encode()).hexdigest()
        while i < len(tokens):
            token = tokens[i]
            if token == "{":
                i += 1; continue
            if token == "}":
                if stack: stack.pop()
                i += 1; continue
            parent = stack[-1] if stack else None
            node = SIRNode(uid("sir"), token, content={"source": source},
                confidence=.55, provenance=Provenance(self.name, now(), (parent.id,) if parent else (), source_hash))
            await self.field.add_node(node); created.append(node)
            if parent: await self.field.add_edge(parent.id, node.id)
            if i + 1 < len(tokens) and tokens[i+1] == "{": stack.append(node); i += 2
            else: i += 1
        return created

class GroundingRefiner(Agent):
    name = "grounding_refiner"
    async def on_event(self, event):
        return None

class ConflictResolver(Agent):
    name = "conflict_resolver"
    async def on_event(self, event):
        return None
    async def propose_conflict(self, subjects, action):
        r = ResolutionNode(uid("res"), "conflict", tuple(subjects), action, .5,
            provenance=Provenance(self.name, now(), tuple(subjects)))
        return await self.field.propose(r)

class BashRealizer(Agent):
    name = "bash_realizer"
    def path_for(self, node):
        parents = self.field.parents(node.id)
        parts = [n.name.lower() for n in reversed(parents)] + [node.name.lower()]
        return "src/" + "/".join(parts) + ".sh"
    async def realize(self, node):
        body = "#!/usr/bin/env bash\nset -euo pipefail\n"
        if node.dimensions.get("behavioral"):
            body += "printf '%s\\n' " + shlex.quote(str(node.dimensions["behavioral"])) + "\n"
        return {"path": self.path_for(node), "content": body, "status": "current", "realizer": self.name}

class PythonRealizer(Agent):
    name = "python_realizer"
    def path_for(self, node):
        parents = self.field.parents(node.id)
        parts = [n.name.lower() for n in reversed(parents)] + [node.name.lower()]
        return "src/" + "/".join(parts) + ".py"
    async def realize(self, node):
        name = re.sub(r"\W+", "_", node.name.lower()).strip("_") or "node"
        body = '"""Generated by Orren."""\n\ndef ' + name + "():\n"
        body += "    return " + repr(node.dimensions.get("behavioral")) + "\n"
        return {"path": self.path_for(node), "content": body, "status": "current", "realizer": self.name}

class VisualProducer(Agent):
    name = "visual_producer"
    async def create_node(self, name, parent_id=None, dimensions=None):
        node = SIRNode(uid("sir"), name, content={"source": "visual"}, confidence=.95,
            provenance=Provenance(self.name, now()))
        if dimensions: node.dimensions.update(dimensions)
        await self.field.add_node(node)
        if parent_id: await self.field.add_edge(parent_id, node.id)
        return node
    async def set_dimension(self, node_id, dimension, value):
        if dimension not in DIMENSIONS: raise ValueError(dimension)
        await self.field.update_node(node_id, dimensions={dimension: value}, confidence=1.0)
    async def move(self, node_id, parent_id):
        self.field.edges = {e for e in self.field.edges if not (e.dst == node_id and e.kind == "contains")}
        await self.field.add_edge(parent_id, node_id)

class VisualObserver:
    def __init__(self, field): self.field = field
    def snapshot(self): return self.field.export()
